# Generated by Django 5.0.3 on 2024-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('population', models.IntegerField()),
                ('literacy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crime', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
