# Generated by Django 5.0.3 on 2024-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='crime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
