# Generated by Django 5.0.3 on 2024-04-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_city_crime'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='education',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='health',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
